<a href="https://colab.research.google.com/github/kimjaewoo1207/2026_1_BDA/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%9E%85%EB%AC%B86%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

       용도별  사고(건)  사망(명)  부상(명)
연도별
2014  비사업용   1940    108   3630
2014   사업용    483     22   1046
2014    기타      3      0      3
2015  비사업용   2172     90   4233
2015   사업용    522     17   1286
2015    기타      7      1      6
2016  비사업용   1832     65   3573
2016   사업용    561     31   1282
2016    기타     40      2     44

In [11]:
df.describe()

             사고(건)       사망(명)        부상(명)
count     9.000000    9.000000     9.000000
mean    840.000000   37.333333  1678.111111
std     888.056868   40.595566  1692.277418
min       3.000000    0.000000     3.000000
25%      40.000000    2.000000    44.000000
50%     522.000000   22.000000  1282.000000
75%    1832.000000   65.000000  3573.000000
max    2172.000000  108.000000  4233.000000

In [12]:
df.T

연도별    2014  2014 2014  2015  2015 2015  2016  2016 2016
용도별    비사업용   사업용   기타  비사업용   사업용   기타  비사업용   사업용   기타
사고(건)  1940   483    3  2172   522    7  1832   561   40
사망(명)   108    22    0    90    17    1    65    31    2
부상(명)  3630  1046    3  4233  1286    6  3573  1282   44

In [13]:
df.dtypes

용도별      object
사고(건)     int64
사망(명)     int64
부상(명)     int64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 2014 to 2016
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   용도별     9 non-null      object
 1   사고(건)   9 non-null      int64
 2   사망(명)   9 non-null      int64
 3   부상(명)   9 non-null      int64
dtypes: int64(3), object(1)
memory usage: 660.0+ bytes

In [15]:
df.sum()

용도별      비사업용사업용기타비사업용사업용기타비사업용사업용기타
사고(건)                           7560
사망(명)                            336
부상(명)                          15103
dtype: object

In [16]:
df.sum(axis=0)

용도별      비사업용사업용기타비사업용사업용기타비사업용사업용기타
사고(건)                           7560
사망(명)                            336
부상(명)                          15103
dtype: object

In [17]:
df.sum(axis=1)

TypeError: can only concatenate str (not "int") to str

In [18]:
df.cumsum(axis=0)

                              용도별  사고(건)  사망(명)  부상(명)
연도별
2014                         비사업용   1940    108   3630
2014                      비사업용사업용   2423    130   4676
2014                    비사업용사업용기타   2426    130   4679
2015                비사업용사업용기타비사업용   4598    220   8912
2015             비사업용사업용기타비사업용사업용   5120    237  10198
2015           비사업용사업용기타비사업용사업용기타   5127    238  10204
2016       비사업용사업용기타비사업용사업용기타비사업용   6959    303  13777
2016    비사업용사업용기타비사업용사업용기타비사업용사업용   7520    334  15059
2016  비사업용사업용기타비사업용사업용기타비사업용사업용기타   7560    336  15103

In [19]:
df.cumsum(axis=1)

TypeError: can only concatenate str (not "int") to str

In [20]:
df.mean()

TypeError: Could not convert ['비사업용사업용기타비사업용사업용기타비사업용사업용기타'] to numeric

In [21]:
df.mean(axis=0)

TypeError: Could not convert ['비사업용사업용기타비사업용사업용기타비사업용사업용기타'] to numeric

In [22]:
df.mean(axis=1)

TypeError: can only concatenate str (not "int") to str

In [24]:
df.mean(axis=None)

TypeError: can only concatenate str (not "int") to str

In [26]:
df.max()

용도별       사업용
사고(건)    2172
사망(명)     108
부상(명)    4233
dtype: object

In [27]:
df.max(axis=0)

용도별       사업용
사고(건)    2172
사망(명)     108
부상(명)    4233
dtype: object

In [29]:
df.max(axis=1)

TypeError: '>=' not supported between instances of 'str' and 'int'

In [30]:
df.meax(axis=None)

AttributeError: 'DataFrame' object has no attribute 'meax'

In [31]:
df.min()

용도별      기타
사고(건)     3
사망(명)     0
부상(명)     3
dtype: object

In [32]:
df.min(axis=0)

용도별      기타
사고(건)     3
사망(명)     0
부상(명)     3
dtype: object

In [33]:
df.min(axis=1)

TypeError: '<=' not supported between instances of 'str' and 'int'

In [34]:
df.min(axis=None)

TypeError: '<=' not supported between instances of 'str' and 'int'

In [35]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연도별
2014    3738
2014    1068
2014       3
2015    4323
2015    1303
2015       7
2016    3638
2016    1313
2016      46
dtype: int64

In [36]:
df.iloc[:, 1:].sum(axis=1)

연도별
2014    5678
2014    1551
2014       6
2015    6495
2015    1825
2015      14
2016    5470
2016    1874
2016      86
dtype: int64

In [37]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

       용도별  사고(건)  사망(명)  부상(명)  재해자수
연도별
2014  비사업용   1940    108   3630  3738
2014   사업용    483     22   1046  1068
2014    기타      3      0      3     3
2015  비사업용   2172     90   4233  4323
2015   사업용    522     17   1286  1303
2015    기타      7      1      6     7
2016  비사업용   1832     65   3573  3638
2016   사업용    561     31   1282  1313
2016    기타     40      2     44    46

In [38]:
df2.sum()

용도별      비사업용사업용기타비사업용사업용기타비사업용사업용기타
사고(건)                           7560
사망(명)                            336
부상(명)                          15103
재해자수                           15439
dtype: object

In [39]:
df2.loc['총계'] = df2.sum(axis=0)
df2

                              용도별  사고(건)  사망(명)  부상(명)   재해자수
연도별
2014                         비사업용   1940    108   3630   3738
2014                          사업용    483     22   1046   1068
2014                           기타      3      0      3      3
2015                         비사업용   2172     90   4233   4323
2015                          사업용    522     17   1286   1303
2015                           기타      7      1      6      7
2016                         비사업용   1832     65   3573   3638
2016                          사업용    561     31   1282   1313
2016                           기타     40      2     44     46
총계    비사업용사업용기타비사업용사업용기타비사업용사업용기타   7560    336  15103  15439

In [40]:
df2 > 10

TypeError: '>' not supported between instances of 'str' and 'int'

In [41]:
df2[df2 > 10]

TypeError: '>' not supported between instances of 'str' and 'int'

In [42]:
df2[ [True]*6 + [False]*7 ]

ValueError: Item wrong length 13 instead of 10.

In [43]:
df2['재해자수'] > 400

연도별
2014     True
2014     True
2014    False
2015     True
2015     True
2015    False
2016     True
2016     True
2016    False
총계       True
Name: 재해자수, dtype: bool

In [44]:
df2[df2['재해자수'] > 400]

                              용도별  사고(건)  사망(명)  부상(명)   재해자수
연도별
2014                         비사업용   1940    108   3630   3738
2014                          사업용    483     22   1046   1068
2015                         비사업용   2172     90   4233   4323
2015                          사업용    522     17   1286   1303
2016                         비사업용   1832     65   3573   3638
2016                          사업용    561     31   1282   1313
총계    비사업용사업용기타비사업용사업용기타비사업용사업용기타   7560    336  15103  15439

In [45]:
df['사망(명)'] == 7

연도별
2014    False
2014    False
2014    False
2015    False
2015    False
2015    False
2016    False
2016    False
2016    False
Name: 사망(명), dtype: bool

In [46]:
df['사망(명)'].isin([7])

연도별
2014    False
2014    False
2014    False
2015    False
2015    False
2015    False
2016    False
2016    False
2016    False
Name: 사망(명), dtype: bool

In [47]:
df['사망(명)'].isin([7, 10])

연도별
2014    False
2014    False
2014    False
2015    False
2015    False
2015    False
2016    False
2016    False
2016    False
Name: 사망(명), dtype: bool

In [48]:
df[ df['사망(명)'].isin([7, 10]) ]

Empty DataFrame
Columns: [용도별, 사고(건), 사망(명), 부상(명)]
Index: []

In [49]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350) ]

       용도별  사고(건)  사망(명)  부상(명)
연도별
2014  비사업용   1940    108   3630
2014   사업용    483     22   1046
2015  비사업용   2172     90   4233
2015   사업용    522     17   1286
2016  비사업용   1832     65   3573
2016   사업용    561     31   1282

In [50]:
df [ df.index.str.contains('3') ]

AttributeError: Can only use .str accessor with string values!

In [51]:
df3 = df.copy()
df3

       용도별  사고(건)  사망(명)  부상(명)
연도별
2014  비사업용   1940    108   3630
2014   사업용    483     22   1046
2014    기타      3      0      3
2015  비사업용   2172     90   4233
2015   사업용    522     17   1286
2015    기타      7      1      6
2016  비사업용   1832     65   3573
2016   사업용    561     31   1282
2016    기타     40      2     44

In [52]:
df3[df3 > 10] = -df3
df3

TypeError: bad operand type for unary -: 'str'

In [63]:
df = pd.DataFrame({'A': range(1, 6),
                  'B': range(6, -3, -2),
                  'C': range(10, 5, -1),
                  'D clmns': range(3, -2, -1),
                  'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [64]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [65]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [66]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [67]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [68]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [69]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [70]:
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [72]:
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [73]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [74]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [75]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [76]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [77]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [78]:
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [79]:
s = "E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [80]:
s = 'E.str.contains("g")'
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [82]:
s = "E.str.endswith('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [83]:
df.head()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [84]:
df.head(7)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [85]:
df.tail()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [86]:
df.tail(6)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [87]:
df.sort_index()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [88]:
df.sort_index(axis=0)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [89]:
df.sort_index(ascending=False)

   A  B   C  D clmns       E
4  5 -2   6       -1  python
3  4  0   7        0      go
2  3  2   8        1  python
1  2  4   9        2    java
0  1  6  10        3  python

In [90]:
df.sort_index(axis=1)

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [91]:
df.sort_index(axis=1, ascending=False)

        E  D clmns   C  B  A
0  python        3  10  6  1
1    java        2   9  4  2
2  python        1   8  2  3
3      go        0   7  0  4
4  python       -1   6 -2  5

In [92]:
df.sort_values(by='사망(명)')

KeyError: '사망(명)'

In [93]:
df.sort_values(by=['사망(명)', '부상(명)'])

KeyError: '사망(명)'

In [95]:
df.sort_values(by='2016년12월', axis=1)

KeyError: '2016년12월'

In [96]:
df.sort_values(by=['2016년12월'], axis=1, ascending=False)

KeyError: '2016년12월'

In [97]:
import numpy as np
import pandas as pd

dates = pd.date_range('20240102', periods=6)
df = pd.DataFrame(np.arange(24).reshape(6, 4), index=dates)
df

             0   1   2   3
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [98]:
df.columns = list('ABCD')
df

             A   B   C   D
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [99]:
s1 = pd.Series([1, 2, 3, 4, 5], index=pd.date_range("20240102", periods=5))
s1

2024-01-02    1
2024-01-03    2
2024-01-04    3
2024-01-05    4
2024-01-06    5
Freq: D, dtype: int64

In [101]:
df["E"] = s1
df

             A   B   C   D    E
2024-01-02   0   1   2   3  1.0
2024-01-03   4   5   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [102]:
df.loc['2024-01-02', 'A'] = 10
df

             A   B   C   D    E
2024-01-02  10   1   2   3  1.0
2024-01-03   4   5   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [103]:
df.loc[dates[1], 'B'] = 50
df

             A   B   C   D    E
2024-01-02  10   1   2   3  1.0
2024-01-03   4  50   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [104]:
df.at[dates[2], df.columns[2]] = 100
df

             A   B    C   D    E
2024-01-02  10   1    2   3  1.0
2024-01-03   4  50    6   7  2.0
2024-01-04   8   9  100  11  3.0
2024-01-05  12  13   14  15  4.0
2024-01-06  16  17   18  19  5.0
2024-01-07  20  21   22  23  NaN

In [105]:
df.at[df.index[-1], df.columns[-1]] = 230
df

             A   B    C   D      E
2024-01-02  10   1    2   3    1.0
2024-01-03   4  50    6   7    2.0
2024-01-04   8   9  100  11    3.0
2024-01-05  12  13   14  15    4.0
2024-01-06  16  17   18  19    5.0
2024-01-07  20  21   22  23  230.0

In [106]:
df.iloc[1, 2] = 60
df

             A   B    C   D      E
2024-01-02  10   1    2   3    1.0
2024-01-03   4  50   60   7    2.0
2024-01-04   8   9  100  11    3.0
2024-01-05  12  13   14  15    4.0
2024-01-06  16  17   18  19    5.0
2024-01-07  20  21   22  23  230.0

In [107]:
df.iat[3, 3] = 150
df

             A   B    C    D      E
2024-01-02  10   1    2    3    1.0
2024-01-03   4  50   60    7    2.0
2024-01-04   8   9  100   11    3.0
2024-01-05  12  13   14  150    4.0
2024-01-06  16  17   18   19    5.0
2024-01-07  20  21   22   23  230.0

In [108]:
df.iloc[:, 4] = [500] * len(df)
df

             A   B    C    D      E
2024-01-02  10   1    2    3  500.0
2024-01-03   4  50   60    7  500.0
2024-01-04   8   9  100   11  500.0
2024-01-05  12  13   14  150  500.0
2024-01-06  16  17   18   19  500.0
2024-01-07  20  21   22   23  500.0

In [109]:
df.iloc[:, 4] = 600
df

             A   B    C    D      E
2024-01-02  10   1    2    3  600.0
2024-01-03   4  50   60    7  600.0
2024-01-04   8   9  100   11  600.0
2024-01-05  12  13   14  150  600.0
2024-01-06  16  17   18   19  600.0
2024-01-07  20  21   22   23  600.0

In [111]:
import numpy as np
import pandas as pd

dates = pd.date_range("20250302", periods=7, freq='W-MON')
df = pd.DataFrame(np.arange(35).reshape(7, 5), index=dates, columns=list("ABCDE"))
df

             A   B   C   D   E
2025-03-03   0   1   2   3   4
2025-03-10   5   6   7   8   9
2025-03-17  10  11  12  13  14
2025-03-24  15  16  17  18  19
2025-03-31  20  21  22  23  24
2025-04-07  25  26  27  28  29
2025-04-14  30  31  32  33  34

In [112]:
subdates = pd.date_range("20250303", periods=5, freq='W-MON')
subdates

DatetimeIndex(['2025-03-03', '2025-03-10', '2025-03-17', '2025-03-24',
               '2025-03-31'],
              dtype='datetime64[ns]', freq='W-MON')

In [113]:
s = pd.Series(np.linspace(10, 17, 5), index=subdates)
s

2025-03-03    10.00
2025-03-10    11.75
2025-03-17    13.50
2025-03-24    15.25
2025-03-31    17.00
Freq: W-MON, dtype: float64

In [114]:
df['F'] = s
df

             A   B   C   D   E      F
2025-03-03   0   1   2   3   4  10.00
2025-03-10   5   6   7   8   9  11.75
2025-03-17  10  11  12  13  14  13.50
2025-03-24  15  16  17  18  19  15.25
2025-03-31  20  21  22  23  24  17.00
2025-04-07  25  26  27  28  29    NaN
2025-04-14  30  31  32  33  34    NaN

In [115]:
df2 = df.copy()
df2.iloc[3, 4] = np.nan
df2.iloc[1, :] = np.nan
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0  10.00
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  13.50
2025-03-24  15.0  16.0  17.0  18.0   NaN  15.25
2025-03-31  20.0  21.0  22.0  23.0  24.0  17.00
2025-04-07  25.0  26.0  27.0  28.0  29.0    NaN
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [116]:
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0  10.00
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  13.50
2025-03-24  15.0  16.0  17.0  18.0   NaN  15.25
2025-03-31  20.0  21.0  22.0  23.0  24.0  17.00
2025-04-07  25.0  26.0  27.0  28.0  29.0    NaN
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [117]:
pd.isna(df2)

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False  False
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False   True
2025-04-14  False  False  False  False  False   True

In [119]:
df2.isna()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False  False
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False   True
2025-04-14  False  False  False  False  False   True

In [120]:
df2.isnull()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False  False
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False   True
2025-04-14  False  False  False  False  False   True

In [121]:
df2.count()

A    6
B    6
C    6
D    6
E    5
F    4
dtype: int64

In [122]:
df2.count(axis=1)

2025-03-03    6
2025-03-10    0
2025-03-17    6
2025-03-24    5
2025-03-31    6
2025-04-07    5
2025-04-14    5
Freq: W-MON, dtype: int64

In [123]:
s = df2.E.value_counts()
s

E
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [124]:
type(s)

pandas.core.series.Series

In [125]:
s[4]

np.int64(1)

In [126]:
s.values

array([1, 1, 1, 1, 1])

In [127]:
df2['D'].value_counts()

D
3.0     1
13.0    1
18.0    1
23.0    1
28.0    1
33.0    1
Name: count, dtype: int64

In [128]:
df2['D'].value_counts().to_frame()

      count
D
3.0       1
13.0      1
18.0      1
23.0      1
28.0      1
33.0      1

In [129]:
df2.E.value_counts(dropna=False)

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [130]:
df2.value_counts(dropna=False)

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   10.00    1
10.0  11.0  12.0  13.0  14.0  13.50    1
15.0  16.0  17.0  18.0  NaN   15.25    1
20.0  21.0  22.0  23.0  24.0  17.00    1
25.0  26.0  27.0  28.0  29.0  NaN      1
30.0  31.0  32.0  33.0  34.0  NaN      1
NaN   NaN   NaN   NaN   NaN   NaN      1
Name: count, dtype: int64

In [132]:
s1 = df2.value_counts()
s1

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   10.0    1
10.0  11.0  12.0  13.0  14.0  13.5    1
20.0  21.0  22.0  23.0  24.0  17.0    1
Name: count, dtype: int64

In [133]:
s1.index

MultiIndex([( 0.0,  1.0,  2.0,  3.0,  4.0, 10.0),
            (10.0, 11.0, 12.0, 13.0, 14.0, 13.5),
            (20.0, 21.0, 22.0, 23.0, 24.0, 17.0)],
           names=['A', 'B', 'C', 'D', 'E', 'F'])

In [134]:
s1.values

array([1, 1, 1])

In [135]:
df2.dropna()

               A     B     C     D     E     F
2025-03-03   0.0   1.0   2.0   3.0   4.0  10.0
2025-03-17  10.0  11.0  12.0  13.0  14.0  13.5
2025-03-31  20.0  21.0  22.0  23.0  24.0  17.0

In [136]:
df2.dropna(axis=0)

               A     B     C     D     E     F
2025-03-03   0.0   1.0   2.0   3.0   4.0  10.0
2025-03-17  10.0  11.0  12.0  13.0  14.0  13.5
2025-03-31  20.0  21.0  22.0  23.0  24.0  17.0

In [137]:
df2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [2025-03-03 00:00:00, 2025-03-10 00:00:00, 2025-03-17 00:00:00, 2025-03-24 00:00:00, 2025-03-31 00:00:00, 2025-04-07 00:00:00, 2025-04-14 00:00:00]

In [139]:
df2[ df2.isna() ] = 500
df2

                A      B      C      D      E       F
2025-03-03    0.0    1.0    2.0    3.0    4.0   10.00
2025-03-10  500.0  500.0  500.0  500.0  500.0  500.00
2025-03-17   10.0   11.0   12.0   13.0   14.0   13.50
2025-03-24   15.0   16.0   17.0   18.0  500.0   15.25
2025-03-31   20.0   21.0   22.0   23.0   24.0   17.00
2025-04-07   25.0   26.0   27.0   28.0   29.0  500.00
2025-04-14   30.0   31.0   32.0   33.0   34.0  500.00

In [140]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list("ABCD"))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [141]:
df.fillna(10)

      A     B     C     D
0  10.0   2.0  10.0   0.0
1   3.0   4.0  10.0   1.0
2  10.0  10.0  10.0  10.0
3  10.0   3.0  10.0   4.0

In [143]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [152]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [144]:
df.fillna('missing', axis=0)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0  missing      1.0
2  missing  missing  missing  missing
3  missing      3.0  missing      4.0

In [146]:
df.fillna('missing', limit=1)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0      NaN      1.0
2      NaN  missing      NaN  missing
3      NaN      3.0      NaN      4.0

In [147]:
df.fillna('missing', limit=1, axis=1)

         A    B        C    D
0  missing  2.0      NaN  0.0
1      3.0  4.0  missing  1.0
2  missing  NaN      NaN  NaN
3  missing  3.0      NaN  4.0

In [148]:
df.fillna('value', axis=1)

       A      B      C      D
0  value    2.0  value    0.0
1    3.0    4.0  value    1.0
2  value  value  value  value
3  value    3.0  value    4.0

In [150]:
values = {"A":100, "B":200, "C":300, "D":400}
df.fillna(value=values)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0  300.0  400.0
3  100.0    3.0  300.0    4.0

In [151]:
df.fillna(value=values, limit=2)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0    NaN  400.0
3    NaN    3.0    NaN    4.0

In [153]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [154]:
s = pd.Series([100, 200, 400], index=list('ACD'))
s

A    100
C    200
D    400
dtype: int64

In [156]:
df.fillna(value=s, limit=1)

       A    B      C      D
0  100.0  2.0  200.0    0.0
1    3.0  4.0    NaN    1.0
2    NaN  NaN    NaN  400.0
3    NaN  3.0    NaN    4.0

In [157]:
df2 = pd.DataFrame(-np.ones((4, 4)), columns=list("ABCE"))
df2

     A    B    C    E
0 -1.0 -1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0

In [159]:
df.fillna(df2)

     A    B    C    D
0 -1.0  2.0 -1.0  0.0
1  3.0  4.0 -1.0  1.0
2 -1.0 -1.0 -1.0  NaN
3 -1.0  3.0 -1.0  4.0

In [160]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [161]:
df.fillna(method='ffill')

/tmp/ipykernel_12421/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [162]:
df.fillna(method='ffill', limit=1)

/tmp/ipykernel_12421/3640860781.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=1)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [163]:
df.fillna(method='bfill', limit=1)

/tmp/ipykernel_12421/3785261496.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', limit=1)

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

In [164]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [165]:
df.mean()

A    3.000000
B    3.000000
C         NaN
D    1.666667
dtype: float64

In [166]:
df.fillna(df.mean())

     A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [167]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [168]:
df.fillna(df.mean()['A':'B'])

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  NaN
3  3.0  3.0 NaN  4.0

In [169]:
df.fillna(df.mean()['D'])

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000  1.666667  1.000000
2  1.666667  1.666667  1.666667  1.666667
3  1.666667  3.000000  1.666667  4.000000

In [170]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [171]:
df.fillna(df.mean()['D'], limit=1)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [172]:
df.fillna(df.mean()['D'], limit=1, axis=0)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [173]:
df.fillna(df.mean()['D'], limit=1, axis=1)

          A    B         C    D
0  1.666667  2.0       NaN  0.0
1  3.000000  4.0  1.666667  1.0
2  1.666667  NaN       NaN  NaN
3  1.666667  3.0       NaN  4.0